### ISSUE TITLE
Update structure to prepare report

### ISSUE THREAD

**Issue by ssteinbuss** [International-Data-Spaces-Association/IDS-Deployment-Scenarios#4]
We should follow a structure somehow like:

# IDS Testbed and deployments report

## Introduction

* what is a data space
* what are cool use cases and why do we need data spaces
* Technically speaking, what is a data space
* Connectors
* MVDS, what are the services we need
* How to join in to Deployment scenarios, call to action

## Foundation - terms and defintions

* there are different things to be known before
* what do you want to do
  * Testing for validation
  * testing for playing around
  * testing for extension
  * provindg services
* Any other ideas?
* include cool figures from Anil and Christoph

## Overview

brief introduction, how to read this section

### IDS Reference testbed

to be explained

### Deployment scenarios

* differentiate between
  * complex techniclogica additions
  * "just" usage of technologies, like IMT is just using the connector in projects

### testbeds

* list and describe the testbeds

## Outlook and next steps

**Comment by anilturkmayali** [comment]
This outline has already been applied in a branch and it will later be used as the backbone of IDS Deployment Scenarios report.
